on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
name: Lint and Build

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Run Linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.61.0
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Build the project
        run: go build -v ./...
